[package]
name = "testi2c"
version = "0.1.0"
authors = ["nate"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i2cdev = "0.4.2"
rppal = "0.11.3"
